
name: Prashant Kikani

title: Prashant Kikani

description: "Prashant Kikani is a software engineer(machine learning) and hobbyist writer. His goal is to make a +ve impact on millions of people's daily lives & to be hyper-optimistic about the future."

avatar: "./assets/dp.jpg"

footer-links:
  email: prashant@kikani.in
  github: prashant-kikani
  kaggle: prashantkikani
  linkedin: prashant-kikani
  x: prashant_kikani

disqus:

google_analytics: UA-180199115-1

url: "https://prashantkikani.com"

baseurl: ""

permalink: /:title

version: v4.1.1

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - rexml
  - kramdown
  - jekyll-redirect-from

redirects:
  - from: "/blog/"
    to: "/blog"
  - from: "/stories/"
    to: "/stories"
  - from: "/questions/"
    to: "/questions"
  - from: "/about/"
    to: "/about"
  - from: "/tic/"
    to: "/tic"
  - from: "/contact/"
    to: "/contact"


# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

include:
  - .htaccess

# https://github.com/kinnetica/jekyll-plugins
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/404.html"
        - "/about.html"
    include_posts:
        - "/index.html"
        - "/blog.html"
        - "/stories.html"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

defaults:
  - scope:
      path: ""
      type: "post"
    values:
      layout: "posts"
      author: "Prashant Kikani"
      description: "Prashant Kikani"
  - scope:
      path: ""
      type: "page"
    values:
      layout: "pages"
      author: "Prashant Kikani"
      description: "Prashant Kikani"
